-- PERMISOS ruguser

---esquema public
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA public TO ruguser;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ruguser;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO ruguser;


-- esquema rug
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA rug TO ruguser;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA rug TO ruguser;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA rug TO ruguser;



